In [37]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [23]:
lsof = pd.read_csv('data/lsof_07052020.txt',sep='\s{2,}')
lsof1 = pd.read_csv('data/lsof_07052020_1.txt',sep=' ')

<ipython-input-23-29261c2b960a>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  lsof = pd.read_csv('data/lsof_07052020.txt',sep='\s{2,}')
<ipython-input-23-29261c2b960a>:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  lsof1 = pd.read_csv('data/lsof_07052020_1.txt',sep='\s{1,}')

ParserError: Expected 9 fields in line 6, saw 10. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

In [10]:
lsof

,COMMAND,PID,USER,FD,TYPE,DEVICE,SIZE/OFF,NODE NAME
0,loginwind,193 vishalendupandey,cwd,DIR,"1,4",704,2 /,NaN
1,loginwind,193 vishalendupandey,txt,REG,"1,4",1261360 1152921500312410237 /System/Library/Co...,None,NaN
2,loginwind,193 vishalendupandey,txt,REG,"1,4",28420,9203200 /Library/Preferences/Logging/.plist-ca...,NaN
3,loginwind,193 vishalendupandey,txt,REG,"1,4",16371 1152921500312273226 /System/Library/Priv...,None,NaN
4,loginwind,193 vishalendupandey,txt,REG,"1,4",3830 1152921500312014940 /System/Library/Input...,None,NaN
...,...,...,...,...,...,...,...,...
10769,lsof,21292 vishalendupandey,0u,CHR,"16,0",0t1963255,1097 /dev/ttys000,NaN
10770,lsof,21292 vishalendupandey,1w,REG,"1,4",0,9592543 /Users/vishalendupandey/projects/pytho...,NaN
10771,lsof,21292 vishalendupandey,2u,CHR,"16,0",0t1963255,1097 /dev/ttys000,NaN
10772,lsof,21292 vishalendupandey,4,PIPE 0xb5c07e703fea25a8,16384,->0xbd21231d7dd4a283,None,NaN
10773,lsof,21292 vishalendupandey,5,PIPE 0xad25b1df3d8e357b,16384,->0x2344a222b170b0b7,None,NaN

In [11]:
lsof['COMMAND'].nunique()

198

In [12]:
lsof['PID'].nunique()

351

In [13]:
lsof.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10774 entries, 0 to 10773
Data columns (total 8 columns):
COMMAND      10774 non-null object
PID          10774 non-null object
USER         10774 non-null object
FD           10772 non-null object
TYPE         10706 non-null object
DEVICE       10242 non-null object
SIZE/OFF     6842 non-null object
NODE NAME    0 non-null float64
dtypes: float64(1), object(7)
memory usage: 673.5+ KB

In [15]:
lsof1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11715 entries, 0 to 11714
Data columns (total 8 columns):
COMMAND      11715 non-null object
PID          11715 non-null object
USER         11715 non-null object
FD           11713 non-null object
TYPE         11640 non-null object
DEVICE       11107 non-null object
SIZE/OFF     7469 non-null object
NODE NAME    0 non-null float64
dtypes: float64(1), object(7)
memory usage: 732.3+ KB

In [19]:
lsof1.groupby('PID').sum().sort_values('NODE NAME',ascending=False)

                        NODE NAME
PID
0                             0.0
488 vishalendupandey          0.0
49u                           0.0
498 vishalendupandey          0.0
495 vishalendupandey          0.0
...                           ...
19561 vishalendupandey        0.0
19540 vishalendupandey        0.0
19332 vishalendupandey        0.0
193 vishalendupandey          0.0
txt                           0.0

[377 rows x 1 columns]

In [22]:
lsof1[['PID','USER']].head()

                    PID USER
0  193 vishalendupandey  cwd
1  193 vishalendupandey  txt
2  193 vishalendupandey  txt
3  193 vishalendupandey  txt
4  193 vishalendupandey  txt

In [34]:
lsof1 = pd.read_fwf('data/lsof_07052020_1.txt')

In [51]:
lsof1.reset_index()

,PID,COMMAND,USER,FD,TYPE,DEVICE,SIZE/OFF,NODE,NAME
0,193,loginwind,vishalendupandey,cwd,DIR,"1,4",704,2,/
1,193,loginwind,vishalendupandey,txt,REG,"1,4",1261360,1152921500312410237,/System/Library/CoreServices/loginwindow.app/C...
2,193,loginwind,vishalendupandey,txt,REG,"1,4",28420,9203200,/Library/Preferences/Logging/.plist-cache.A5Ti...
3,193,loginwind,vishalendupandey,txt,REG,"1,4",16371,1152921500312273226,/System/Library/PrivateFrameworks/BatteryUIKit...
4,193,loginwind,vishalendupandey,txt,REG,"1,4",3830,1152921500312014940,/System/Library/Input Methods/TYIM.app/Content...
...,...,...,...,...,...,...,...,...,...
11710,405,lsof,vishalendupandey,0u,CHR,"16,0",t2255613,1097,/dev/ttys000
11711,405,lsof,vishalendupandey,1w,REG,"1,4",0,9593055,/Users/vishalendupandey/projects/python/jupyte...
11712,405,lsof,vishalendupandey,2u,CHR,"16,0",t2255613,1097,/dev/ttys000
11713,405,lsof,vishalendupandey,4,PIPE,0x342a1a537786da81,16384,NaN,->0xbea5279b4dd8609
11714,405,lsof,vishalendupandey,5,PIPE,0xc999697695a6af69,16384,NaN,->0x20aecf49b2bdba18

In [61]:
lsof1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11715 entries, 0 to 11714
Data columns (total 9 columns):
PID         11715 non-null int64
COMMAND     11715 non-null object
USER        11715 non-null object
FD          11715 non-null object
TYPE        11715 non-null object
DEVICE      11384 non-null object
SIZE/OFF    11413 non-null object
NODE        10917 non-null object
NAME        11564 non-null object
dtypes: int64(1), object(8)
memory usage: 823.8+ KB

In [65]:
lsof1[lsof1['COMMAND']=='idea']

,PID,COMMAND,USER,FD,TYPE,DEVICE,SIZE/OFF,NODE,NAME
10989,363,idea,vishalendupandey,cwd,DIR,"1,4",480,1646117,/Applications/IntelliJ IDEA CE.app/Contents/bin
10990,363,idea,vishalendupandey,txt,REG,"1,4",127840,1646895,/Applications/IntelliJ IDEA CE.app/Contents/Ma...
10991,363,idea,vishalendupandey,txt,REG,"1,4",28420,9203200,/Library/Preferences/Logging/.plist-cache.A5Ti...
10992,363,idea,vishalendupandey,txt,REG,"1,4",28484912,1152921500312401253,/usr/share/icu/icudt64l.dat
10993,363,idea,vishalendupandey,txt,REG,"1,4",82992,1646521,/Applications/IntelliJ IDEA CE.app/Contents/jb...
...,...,...,...,...,...,...,...,...,...
11668,363,idea,vishalendupandey,597u,REG,"1,4",2000,9593036,/Users/vishalendupandey/Library/Saved Applicat...
11669,363,idea,vishalendupandey,598r,REG,"1,4",2052,1648839,/Applications/IntelliJ IDEA CE.app/Contents/pl...
11670,363,idea,vishalendupandey,599r,REG,"1,4",163015,1648838,/Applications/IntelliJ IDEA CE.app/Contents/pl...
11671,363,idea,vishalendupandey,600w,REG,"1,4",1315,9593037,/Users/vishalendupandey/Library/Saved Applicat...
11672,363,idea,vishalendupandey,601u,REG,"1,4",6176,9593038,/Users/vishalendupandey/Library/Saved Applicat...

In [101]:
lsof1 = pd.DataFrame()
cols=['COMMAND' ,'PID', 'USER', 'FD' ,'TYPE' ,'DEVICE' \
               ,'SIZE/OFF' ,'NODE', 'NAME1' ,'NAME2']
lsof1 = pd.read_csv('data/lsof_07052020_1.txt',sep="\s+",\
                    header=None,skiprows=1,names=cols)

In [102]:
lsof1

,COMMAND,PID,USER,FD,TYPE,DEVICE,SIZE/OFF,NODE,NAME1,NAME2
0,loginwind,193,vishalendupandey,cwd,DIR,"1,4",704,2,/,NaN
1,loginwind,193,vishalendupandey,txt,REG,"1,4",1261360,1152921500312410237,/System/Library/CoreServices/loginwindow.app/C...,NaN
2,loginwind,193,vishalendupandey,txt,REG,"1,4",28420,9203200,/Library/Preferences/Logging/.plist-cache.A5Ti...,NaN
3,loginwind,193,vishalendupandey,txt,REG,"1,4",16371,1152921500312273226,/System/Library/PrivateFrameworks/BatteryUIKit...,NaN
4,loginwind,193,vishalendupandey,txt,REG,"1,4",3830,1152921500312014940,/System/Library/Input,Methods/TYIM.app/Contents/PlugIns/TYIM_Extensi...
...,...,...,...,...,...,...,...,...,...,...
11710,lsof,21405,vishalendupandey,0u,CHR,"16,0",0t2255613,1097,/dev/ttys000,NaN
11711,lsof,21405,vishalendupandey,1w,REG,"1,4",0,9593055,/Users/vishalendupandey/projects/python/jupyte...,NaN
11712,lsof,21405,vishalendupandey,2u,CHR,"16,0",0t2255613,1097,/dev/ttys000,NaN
11713,lsof,21405,vishalendupandey,4,PIPE,0x342a1a537786da81,16384,->0xbea5279b4dd8609,NaN,NaN
11714,lsof,21405,vishalendupandey,5,PIPE,0xc999697695a6af69,16384,->0x20aecf49b2bdba18,NaN,NaN

In [115]:
lsof1.groupby('PID').get_group(21363)

,COMMAND,PID,USER,FD,TYPE,DEVICE,SIZE/OFF,NODE,NAME1,NAME2
10989,idea,21363,vishalendupandey,cwd,DIR,"1,4",480,1646117,/Applications/IntelliJ,IDEA
10990,idea,21363,vishalendupandey,txt,REG,"1,4",127840,1646895,/Applications/IntelliJ,IDEA
10991,idea,21363,vishalendupandey,txt,REG,"1,4",28420,9203200,/Library/Preferences/Logging/.plist-cache.A5Ti...,NaN
10992,idea,21363,vishalendupandey,txt,REG,"1,4",28484912,1152921500312401253,/usr/share/icu/icudt64l.dat,NaN
10993,idea,21363,vishalendupandey,txt,REG,"1,4",82992,1646521,/Applications/IntelliJ,IDEA
...,...,...,...,...,...,...,...,...,...,...
11668,idea,21363,vishalendupandey,597u,REG,"1,4",2000,9593036,/Users/vishalendupandey/Library/Saved,Application
11669,idea,21363,vishalendupandey,598r,REG,"1,4",2052,1648839,/Applications/IntelliJ,IDEA
11670,idea,21363,vishalendupandey,599r,REG,"1,4",163015,1648838,/Applications/IntelliJ,IDEA
11671,idea,21363,vishalendupandey,600w,REG,"1,4",1315,9593037,/Users/vishalendupandey/Library/Saved,Application
11672,idea,21363,vishalendupandey,601u,REG,"1,4",6176,9593038,/Users/vishalendupandey/Library/Saved,Application

In [119]:
lsof1.groupby('PID').get_group(21363).groupby('TYPE').count()

        COMMAND  PID  USER   FD  DEVICE  SIZE/OFF  NODE  NAME1  NAME2
TYPE
CHR           5    5     5    5       5         5     5      5      0
DIR           1    1     1    1       1         1     1      1      1
IPv4          3    3     3    3       3         3     3      3      3
KQUEUE        2    2     2    2       2         2     0      0      0
PIPE          7    7     7    7       7         7     7      0      0
REG         662  662   662  662     662       662   662    662    616
systm         1    1     1    1       1         1     1      1      1
unix          3    3     3    3       3         3     3      0      0

In [38]:
lsof1 = pd.DataFrame()
cols=['COMMAND' ,'PID', 'USER', 'FD' ,'TYPE' ,'DEVICE' \
               ,'SIZE/OFF' ,'NODE', 'NAME1' ,'NAME2']
lsof1 = pd.read_csv('data/lsof_07052020_1.txt',sep="\s+",\
                    header=None,skiprows=1,names=cols)
tcp = lsof1.groupby('NODE').get_group('TCP')
tcp_Est = tcp[tcp['NAME2']!='(LISTEN)']
tcp_Est['FROM_ADDR'] = tcp_Est['NAME1'].str.split('->').str.get(0)
tcp_Est['TO_ADDR'] = tcp_Est['NAME1'].str.split('->').str.get(1)
tcp_Est

,COMMAND,PID,USER,FD,TYPE,DEVICE,SIZE/OFF,NODE,NAME1,NAME2,FROM_ADDR,TO_ADDR
952,identitys,505,vishalendupandey,43u,IPv6,0xfd4cf872183fde37,0t0,TCP,vishalendus-macbook-pro.local:1024->[fe80:10::...,(ESTABLISHED),vishalendus-macbook-pro.local:1024,[fe80:10::c06a:ecd4:d425:d206]:1024
953,identitys,505,vishalendupandey,44u,IPv6,0xfd4cf872183fe457,0t0,TCP,vishalendus-macbook-pro.local:blackjack->[fe80...,(ESTABLISHED),vishalendus-macbook-pro.local:blackjack,[fe80:10::c06a:ecd4:d425:d206]:61295
954,identitys,505,vishalendupandey,45u,IPv6,0xfd4cf872183fe457,0t0,TCP,vishalendus-macbook-pro.local:blackjack->[fe80...,(ESTABLISHED),vishalendus-macbook-pro.local:blackjack,[fe80:10::c06a:ecd4:d425:d206]:61295
4169,WhatsApp,1609,vishalendupandey,59u,IPv6,0xfd4cf872185df817,0t0,TCP,2603-6000-b700-0034-3011-b90e-ac6f-45af.res6.s...,(ESTABLISHED),2603-6000-b700-0034-3011-b90e-ac6f-45af.res6.s...,whatsapp-cdn6-shv-01-ort2.fbcdn.net:https
4835,Microsoft,1612,vishalendupandey,50u,IPv4,0xfd4cf871f159dae7,0t0,TCP,192.168.1.9:49349->104.42.252.157:https,(ESTABLISHED),192.168.1.9:49349,104.42.252.157:https
...,...,...,...,...,...,...,...,...,...,...,...,...
10880,python3.8,21309,vishalendupandey,51u,IPv4,0xfd4cf8720c960627,0t0,TCP,localhost:57664->localhost:57695,(ESTABLISHED),localhost:57664,localhost:57695
10883,python3.8,21309,vishalendupandey,54u,IPv4,0xfd4cf8720c95fc47,0t0,TCP,localhost:57668->localhost:57696,(ESTABLISHED),localhost:57668,localhost:57696
10884,python3.8,21309,vishalendupandey,55u,IPv4,0xfd4cf8720c950c47,0t0,TCP,localhost:57665->localhost:57697,(ESTABLISHED),localhost:57665,localhost:57697
10885,python3.8,21309,vishalendupandey,56u,IPv4,0xfd4cf87218deaae7,0t0,TCP,localhost:57666->localhost:57698,(ESTABLISHED),localhost:57666,localhost:57698
10886,python3.8,21309,vishalendupandey,57u,IPv4,0xfd4cf8720c94eea7,0t0,TCP,localhost:57668->localhost:57699,(ESTABLISHED),localhost:57668,localhost:57699

In [39]:

tcp_Est['TO_PORT'] = tcp_Est['TO_ADDR'].str.rsplit(':',n=1).str.get(1)
tcp_Est['TO_IP'] = tcp_Est['TO_ADDR'].str.rsplit(':',n=1).str.get(0)
tcp_Est['FROM_PORT'] = tcp_Est['FROM_ADDR'].str.rsplit(':',n=1).str.get(1)
tcp_Est['FROM_IP'] = tcp_Est['FROM_ADDR'].str.rsplit(':',n=1).str.get(0)
tcp_Est.drop('TO_ADDR',axis=1,inplace=True)
tcp_Est.drop('FROM_ADDR',axis=1,inplace=True)

In [40]:
tcp_Est

,COMMAND,PID,USER,FD,TYPE,DEVICE,SIZE/OFF,NODE,NAME1,NAME2,TO_PORT,TO_IP,FROM_PORT,FROM_IP
952,identitys,505,vishalendupandey,43u,IPv6,0xfd4cf872183fde37,0t0,TCP,vishalendus-macbook-pro.local:1024->[fe80:10::...,(ESTABLISHED),1024,[fe80:10::c06a:ecd4:d425:d206],1024,vishalendus-macbook-pro.local
953,identitys,505,vishalendupandey,44u,IPv6,0xfd4cf872183fe457,0t0,TCP,vishalendus-macbook-pro.local:blackjack->[fe80...,(ESTABLISHED),61295,[fe80:10::c06a:ecd4:d425:d206],blackjack,vishalendus-macbook-pro.local
954,identitys,505,vishalendupandey,45u,IPv6,0xfd4cf872183fe457,0t0,TCP,vishalendus-macbook-pro.local:blackjack->[fe80...,(ESTABLISHED),61295,[fe80:10::c06a:ecd4:d425:d206],blackjack,vishalendus-macbook-pro.local
4169,WhatsApp,1609,vishalendupandey,59u,IPv6,0xfd4cf872185df817,0t0,TCP,2603-6000-b700-0034-3011-b90e-ac6f-45af.res6.s...,(ESTABLISHED),https,whatsapp-cdn6-shv-01-ort2.fbcdn.net,57332,2603-6000-b700-0034-3011-b90e-ac6f-45af.res6.s...
4835,Microsoft,1612,vishalendupandey,50u,IPv4,0xfd4cf871f159dae7,0t0,TCP,192.168.1.9:49349->104.42.252.157:https,(ESTABLISHED),https,104.42.252.157,49349,192.168.1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10880,python3.8,21309,vishalendupandey,51u,IPv4,0xfd4cf8720c960627,0t0,TCP,localhost:57664->localhost:57695,(ESTABLISHED),57695,localhost,57664,localhost
10883,python3.8,21309,vishalendupandey,54u,IPv4,0xfd4cf8720c95fc47,0t0,TCP,localhost:57668->localhost:57696,(ESTABLISHED),57696,localhost,57668,localhost
10884,python3.8,21309,vishalendupandey,55u,IPv4,0xfd4cf8720c950c47,0t0,TCP,localhost:57665->localhost:57697,(ESTABLISHED),57697,localhost,57665,localhost
10885,python3.8,21309,vishalendupandey,56u,IPv4,0xfd4cf87218deaae7,0t0,TCP,localhost:57666->localhost:57698,(ESTABLISHED),57698,localhost,57666,localhost
10886,python3.8,21309,vishalendupandey,57u,IPv4,0xfd4cf8720c94eea7,0t0,TCP,localhost:57668->localhost:57699,(ESTABLISHED),57699,localhost,57668,localhost

In [47]:
ip_summary = pd.DataFrame(tcp_Est.groupby(['FROM_IP','TO_IP','NAME2']).COMMAND.count())

In [48]:
ip_summary

                                                                                                                     COMMAND
FROM_IP                                            TO_IP                                              NAME2
192.168.1.9                                        104.16.0.35                                        (ESTABLISHED)        1
                                                   104.244.42.130                                     (ESTABLISHED)        1
                                                   104.244.42.66                                      (ESTABLISHED)        1
                                                   104.42.252.157                                     (ESTABLISHED)        1
                                                   151.101.1.69                                       (ESTABLISHED)        1
                                                   197.164.154.104.bc.googleusercontent.com           (ESTABLISHED)        1
                                                   52.109.12.9                                        (ESTABLISHED)        2
                                                   a104-124-8-95.deploy.static.akamaitechnologies.com (ESTABLISHED)        1
                                                   a23-65-241-243.deploy.static.akamaitechnologies... (ESTABLISHED)        1
                                                   customer.clientshostname.com                       (ESTABLISHED)        1
                                                                                                      (SYN_SENT)           1
                                                   ec2-34-237-73-95.compute-1.amazonaws.com           (ESTABLISHED)        1
                                                   ec2-35-174-127-31.compute-1.amazonaws.com          (ESTABLISHED)        2
                                                   server-52-85-90-214.ord53.r.cloudfront.net         (ESTABLISHED)        1
2603-6000-b700-0034-3011-b90e-ac6f-45af.res6.sp... [2606:4700:10::6814:2fa6]                          (ESTABLISHED)        1
                                                   [2606:4700:10::6814:30a6]                          (ESTABLISHED)        1
                                                   [2606:4700::6812:1ad3]                             (ESTABLISHED)        1
                                                   [2606:4700::6812:1bd3]                             (ESTABLISHED)        1
                                                   [2620:108:700f::22df:8202]                         (ESTABLISHED)        1
                                                   [2620:108:700f::3422:9ea1]                         (ESTABLISHED)        1
                                                   [2620:109:c002::6cae:a0a]                          (ESTABLISHED)        2
                                                   [2a04:4e42:3e::343]                                (ESTABLISHED)        1
                                                   edge-star6-shv-01-ort2.facebook.com                (ESTABLISHED)        1
                                                   ie-in-xbc.1e100.net                                (ESTABLISHED)        2
                                                   ord36s01-in-x05.1e100.net                          (ESTABLISHED)        1
                                                   ord37s19-in-x05.1e100.net                          (ESTABLISHED)        1
                                                   whatsapp-cdn6-shv-01-ort2.fbcdn.net                (ESTABLISHED)        1
localhost                                          localhost                                          (ESTABLISHED)       30
vishalendus-macbook-pro.local                      [fe80:10::c06a:ecd4:d425:d206]                     (ESTABLISHED)        3